services:
  web:
    build: app/TeamMembers
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  db:
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"

    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    ports:
      - 1433:1433
    volumes:
      - ~/.db_data/data:/var/opt/mssql/data
      - ~/.db_data/logs:/var/opt/mssql/logs
    